spring:
  application:
    name: order-service
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board

  cache:
    type: redis
    data:
      redis:
        host: localhost
        port: 6379
        username: default
        password: systempass

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka
